//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifePunch_Quickjoin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb1.lifepunch.net")]
        public string Jailbreak1Host {
            get {
                return ((string)(this["Jailbreak1Host"]));
            }
            set {
                this["Jailbreak1Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb2.lifepunch.net")]
        public string Jailbreak2Host {
            get {
                return ((string)(this["Jailbreak2Host"]));
            }
            set {
                this["Jailbreak2Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb3.lifepunch.net")]
        public string Jailbreak3Host {
            get {
                return ((string)(this["Jailbreak3Host"]));
            }
            set {
                this["Jailbreak3Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb4.lifepunch.net")]
        public string Jailbreak4Host {
            get {
                return ((string)(this["Jailbreak4Host"]));
            }
            set {
                this["Jailbreak4Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb5.lifepunch.net")]
        public string Jailbreak5Host {
            get {
                return ((string)(this["Jailbreak5Host"]));
            }
            set {
                this["Jailbreak5Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb6.lifepunch.net")]
        public string Jailbreak6Host {
            get {
                return ((string)(this["Jailbreak6Host"]));
            }
            set {
                this["Jailbreak6Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb7.lifepunch.net")]
        public string Jailbreak7Host {
            get {
                return ((string)(this["Jailbreak7Host"]));
            }
            set {
                this["Jailbreak7Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb8.lifepunch.net")]
        public string Jailbreak8Host {
            get {
                return ((string)(this["Jailbreak8Host"]));
            }
            set {
                this["Jailbreak8Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jb9.lifepunch.net")]
        public string Jailbreak9Host {
            get {
                return ((string)(this["Jailbreak9Host"]));
            }
            set {
                this["Jailbreak9Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dr1.lifepunch.net")]
        public string Deathrun1Host {
            get {
                return ((string)(this["Deathrun1Host"]));
            }
            set {
                this["Deathrun1Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dr2.lifepunch.net")]
        public string Deathrun2Host {
            get {
                return ((string)(this["Deathrun2Host"]));
            }
            set {
                this["Deathrun2Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dr3.lifepunch.net")]
        public string Deathrun3Host {
            get {
                return ((string)(this["Deathrun3Host"]));
            }
            set {
                this["Deathrun3Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dr4.lifepunch.net")]
        public string Deathrun4Host {
            get {
                return ((string)(this["Deathrun4Host"]));
            }
            set {
                this["Deathrun4Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dr5.lifepunch.net")]
        public string Deathrun5Host {
            get {
                return ((string)(this["Deathrun5Host"]));
            }
            set {
                this["Deathrun5Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gg1.lifepunch.net")]
        public string Gungame1Host {
            get {
                return ((string)(this["Gungame1Host"]));
            }
            set {
                this["Gungame1Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gg2.lifepunch.net")]
        public string Gungame2Host {
            get {
                return ((string)(this["Gungame2Host"]));
            }
            set {
                this["Gungame2Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bh1.lifepunch.net")]
        public string Bunnyhop1Host {
            get {
                return ((string)(this["Bunnyhop1Host"]));
            }
            set {
                this["Bunnyhop1Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bh2.lifepunch.net")]
        public string Bunnyhop2Host {
            get {
                return ((string)(this["Bunnyhop2Host"]));
            }
            set {
                this["Bunnyhop2Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bh3.lifepunch.net")]
        public string Bunnyhop3Host {
            get {
                return ((string)(this["Bunnyhop3Host"]));
            }
            set {
                this["Bunnyhop3Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cn.lifepunch.net")]
        public string CinemaHost {
            get {
                return ((string)(this["CinemaHost"]));
            }
            set {
                this["CinemaHost"] = value;
            }
        }
    }
}
